name = "momento-cloudflare-worker-http"
main = "src/worker.ts"
compatibility_date = "2023-07-10"

[vars]
MOMENTO_REST_ENDPOINT = "https://api.cache.cell-us-east-1-1.prod.a.momentohq.com"
MOMENTO_CACHE_NAME = "cache"
